### PR TITLE
(#26): Update button navigation and add SignIn/Signup stacks

### LINKED ISSUE #26: Update button navigation on HomeScreen.tsx
**Navigate to correct paths in HomeScreen.tsx**
Currently the paths are navigation to root as default and need to be updated.

**Describe the solution you'd like**
- Sign-In button needs to navigate to SignInScreen.tsx
- Sign-up button needs to navigate to SignUpScreen.tsx

**Additional context**
-[These docs](https://reactnavigation.org/docs/stack-navigator/) might be helpful

### PR DESCRIPTION
**Pull request by honsq90**
Closes #26 

## Changes Proposed in this Pull Request:
- Updated the navigator mappings `"SignIn" -> SignInScreen` and `"SignUp" -> SignUpScreen`
- Updated the buttons to navigate to `SignIn` and `SignUp` respectively

@BekahHW

### CODE REVIEW

**Comment by BekahHW** [comment]
Thanks for working on this! I'm going to review it as soon as I can and get back to you.

**Comment by BekahHW** [comment]
Hey! Sorry for the delay. Any idea why so many files have been changed here?

**Comment by honsq90** [comment]
No worries! Let me see what's going on, I did notice that those file changes were detected locally, but I didn't commit them. Let me rebase my branch and try again

**Comment by honsq90** [comment]
I've updated the branch now, I had some config differences between command line and VSCode which is why it committed the files in node_modules

**Comment by honsq90** [comment]
I also made a change to fix up the flex styling for the SignIn and SignUp screen. `height` was working fine for Chrome, but in iOS it seemed to stretch more than required.

Before:
Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-06 at 11 10 24

After:
Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-06 at 11 10 38

**Comment by BekahHW** [comment]
This is great! Thank you!

**Pull request merged**
