### PR TITLE
WIP: Positivity ToolBox Screen

### PR DESCRIPTION
**Pull request by dominicduffin1**
Work In Progress on #21 

## Changes Proposed in this Pull Request:
- New screen: Positivity Toolbox
- Six cards with images, titles and placeholder subtitles
- `react-native-svg` installed

## Issues/ToDo:
- Breathing card has SVG, the rest are currently PNG using `resizeMode="contain"` but these are not behaving on Android, SVGs probably the way to go for all. Ideally images need to be more responsive.
- `ScrollView` not working properly on Android, [this](https://stackoverflow.com/questions/46805135/scrollview-with-flex-1-makes-it-un-scrollable) might be relevant but I can't figure it out atm.

@BekahHW

### CODE REVIEW

**Comment by BekahHW** [comment]
@dominicduffin1 this is looking awesome! Thanks for all your hard work.

I think a couple of things are happening with the scrollView:

For ref: https://reactnative.dev/docs/scrollview

1. Let's import Constants: `import Constants from 'expo-constants'`
2. I think there are some conflicting styles:
 - For the container, we're going to use the Constants for the marginTop: `marginTop: Constants.statusBarHeight`,
 - I think what we want here for margin for the ScrollView (`contentContainer: marginHorizontal: 20`)
3. Add` <SafeAreaView>` like the ref link above. You might be able to replace that first view with the SafeAreaView.

Let me know if you have questions

**Comment by dominicduffin1** [comment]
@BekahHW  Thank you for the suggestions for the `<ScrollView>`, I've worked through that and it is now working on Android!

**Comment by BekahHW** [comment]
This is looking awesome! I think the bottom could use a little bit of padding. 

I'm noticing a little bit of issues with the SVGs either extending past the container or getting cut off. 

Is this happening on Android?

I think it's ok to make them bigger bc well have lots of space there. image

**Comment by dominicduffin1** [comment]
@BekahHW I can add some padding at the bottom!

The images are the final thing, I need to convert the rest to SVG and add a bit more space for at least some of them.

**Comment by dominicduffin1** [comment]
@BekahHW 

I think the SVGs are all looking good now, and I've added padding at the bottom.

This is what it looks like on my Android:
thumbnail_Screenshot_20210115-150255
thumbnail_Screenshot_20210115-150243

**Comment by dominicduffin1** [comment]
@BekahHW Just wondering, is everything ok now with this PR?

**Comment by BekahHW** [comment]
Hey! I'm having some image overflow on the cards on my devices. I think for this PR, we could add left and right padding: 15.

If you could do that, then I'm happy to pull the changes and merge it in! Thanks for all your hard work.

**Comment by dominicduffin1** [comment]
@BekahHW I've added 15 left and right padding to the cards, I think that helps.

**Comment by BekahHW** [comment]
:tada::tada::tada: Thank you so much, @dominicduffin1 :tada::tada::tada:

**Pull request merged**
